"use client"

import { editUserMessage } from "@/app/(dashboard)/playground/actions"
import { PREFERENCES_DEFAULT_VALUES } from "@/components/views/playground/utils"
import { GetChatHistoryResponse } from "@/lib/data/playground"
import { Conversation, FC, PlaygroundSettings } from "@/utils/types"
import React, {
  createContext,
  RefObject,
  useContext,
  useMemo,
  useRef,
  useState,
} from "react"

export type SettingsKey = keyof PlaygroundSettings

type PlaygroundContextType = {
  textBoxValue: string
  settings: PlaygroundSettings
  conversations: Conversation[]
  id: GetChatHistoryResponse["id"]
  scrollerRef?: RefObject<HTMLDivElement>
  setTextBoxValue: (value: string) => void
  setPreferences: (settings: PlaygroundSettings) => void
  //   creates a new entry in conversations.history_code.messages
  editMessage: (formdata: FormData) => string //returns id the generated user_message
  /**
   *   create new entry in conversation =>
   *   conversations = {
   *       ...converations,
   *       history_code(auto_generated from length of existing converations): {
   *           messages: {
   *               id (auto generate usermessage id): {
   *                   user_message: UserMessage // generated with just message
   *                   sate_responses: SateMessages // generated with the autogenerated usermessage id
   *               }
   *           }
   *       }
   *   }
   *
   *
   *
   */
  addNewMessage: (message: string) => string //returns id of the new conversation
  createResponseEntry: (historyCode: string, userMessage: string) => string // return the response
  updateResponse: (
    response: string,
    historyCode: string,
    userMessage: string
  ) => boolean //pops the last response, updates it and put it back.
}

const PlaygroundContext = createContext<PlaygroundContextType>({
  textBoxValue: "",
  settings: PREFERENCES_DEFAULT_VALUES,
  conversations: [],
  id: "",
  setTextBoxValue: () => {},
  setPreferences: () => {},
  editMessage: () => "",
  addNewMessage: () => "",
  createResponseEntry: () => "",
  updateResponse: () => false,
})

export const usePlayground = () => {
  const context = useContext(PlaygroundContext)
  if (!context) {
    throw new Error(
      "usePlayground should be called inside a PlaygroundProvider"
    )
  }
  return context
}

type Props = {
  chatHistory: GetChatHistoryResponse
}

const PlaygroundProvider: FC<Props> = ({ children, chatHistory }) => {
  const chatScrollerRef = useRef<HTMLDivElement>(null)

  const [textBoxValue, setTextBoxValue] = useState("")
  const [settings, setSettings] = useState<PlaygroundSettings>(
    PREFERENCES_DEFAULT_VALUES
  )
  const [conversations] = useState<Conversation[]>(() =>
    chatHistory.conversations.map((conversation, idx) => ({
      ...conversation,
      message_history_code: conversation.message_history_code || idx.toString(),
    }))
  )

  const id = useMemo(() => chatHistory.id, [chatHistory.id])

  const setPreferences = (settings: PlaygroundSettings) => {
    setSettings(settings)
  }
  const addNewMessage = (message: string) => {
    console.log({ conversations, message })
    // conversation id = Object.keys(conversation).length.toString();
    // generate UserMessage obj
    // generate SateMessage obj with id: "" and isLoading: true
    // create conversation block with shape {message_history_code: id, messages: {[UserMessage.id]: {UserMessage, [SateMessage]}}}
    return ""
  }
  const editMessage = (formdata: FormData) => {
    console.log(Object.fromEntries(formdata))
    editUserMessage(formdata)

    return ""
  }

  const createResponseEntry = () => ""
  const updateResponse = () => false

  return (
    <PlaygroundContext.Provider
      value={{
        textBoxValue,
        settings,
        conversations,
        id,
        scrollerRef: chatScrollerRef,
        setTextBoxValue,
        setPreferences,
        editMessage,
        addNewMessage,
        createResponseEntry,
        updateResponse,
      }}
    >
      {children}
    </PlaygroundContext.Provider>
  )
}

export default PlaygroundProvider
